# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PlatformRegisterReq.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'PlatformRegisterReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19PlatformRegisterReq.proto\x12\x05proto\"\xa3\x02\n\x13PlatformRegisterReq\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x0f\n\x07open_id\x18\x03 \x01(\t\x12\x11\n\tavatar_id\x18\x05 \x01(\r\x12\x15\n\rplatform_type\x18\x06 \x01(\r\x12\x17\n\x0fplatform_sdk_id\x18\x07 \x01(\r\x12\x36\n\rusing_version\x18\r \x01(\x0e\x32\x1f.proto.EAuth_ClientUsingVersion\x12\x1e\n\x16platform_register_info\x18\x0e \x01(\x0c\x12\x10\n\x08language\x18\x0f \x01(\t\x12\x12\n\nunknown_16\x18\x10 \x01(\r\x12\x12\n\nunknown_17\x18\x11 \x01(\r*\xae\x01\n\x18\x45\x41uth_ClientUsingVersion\x12\x1b\n\x17\x43lientUsingVersion_NONE\x10\x00\x12\x1d\n\x19\x43lientUsingVersion_NORMAL\x10\x01\x12\x1a\n\x16\x43lientUsingVersion_MAX\x10\x02\x12\x1a\n\x16\x43lientUsingVersion_FFI\x10\x03\x12\x1e\n\x1a\x43lientUsingVersion_MAX_HPE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'register_req_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EAUTH_CLIENTUSINGVERSION']._serialized_start=331
  _globals['_EAUTH_CLIENTUSINGVERSION']._serialized_end=505
  _globals['_PLATFORMREGISTERREQ']._serialized_start=37
  _globals['_PLATFORMREGISTERREQ']._serialized_end=328
# @@protoc_insertion_point(module_scope)
